---
- name: Get secrets from vault
  hosts: all
  gather_facts: false
  roles:
    - role: bmstu.vats.init
      vault_path_inventory: bots/data/deploy,inventory-secrets.yaml
      vault_path_secrets:   bots/data/rusengineer23,secrets.yaml
      validate_certs: false
  tasks:
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present
      
    - name: Ensure hashdb.sqlite exists
      copy:
        content: ""
        dest: ~/hashdb.sqlite
        force: false

    - name: Run bot docker service
      docker_swarm_service:
        name: rusengineer23-bot
        image: twobrowin/rusengineer23-bot:1.0.11
        mounts:
          - source: /home/user/hashdb.sqlite
            target: /hashdb.sqlite
            type: bind
        env:
          TZ: "Europe/Moscow"
          
          BOT_TOKEN:       "{{ secrets.bot_token }}"
          SHEETS_ACC_JSON: "{{ secrets.sheet_acc_json | string }}"
          SHEETS_LINK:     "{{ secrets.sheets_link }}"

          SWITCH_UPDATE_TIME:   '15'
          SETTINGS_UPDATE_TIME: '35'
          
          HASH_DB: /hashdb.sqlite
